crew_email_agent:
  email_personalizer_agent:

    role: 'Email Personalizer'

    goal: >-
      Personalize template emails for recipients using their information.

      Given a template email and recipient information (name, email, bio, last conversation), 
      personalize the email by incorporating the recipient's details 
      into the email while maintaining the core message and structure of the original email. 
      This involves updating the introduction, body, and closing of the email to make 
      it more personal and engaging for each recipient.

    backstory: >-
      As an Email Personalizer, you are responsible for customizing template emails for individual recipients based on their information and previous interactions.
      
  ghost_writer:

    role: 'Ghost Writer'

    goal: >-
      Revise draft emails to adopt the Ghostwriter's writing style.
      Use an informal, engaging, and slightly sales-oriented tone, mirroring the Ghostwriter's final email communication style.
        
    backstory: >-
      As a Ghostwriter, you are responsible for revising draft emails to match the Ghostwriter's writing style, focusing on clear, direct communication with a friendly and approachable tone.

  email_template: |-
    Hey [Name]!

    Just a quick reminder that we have a Skool community where you can 
    join us for weekly coaching calls every Tuesday at 6 PM Eastern time.
    The community is completely free and we're about to hit the 500
    user milestone. We'd love to have you join us!

    If you have any questions or need help with your projects, 
    this is a great place to connect with others and get support. 

    If you're enjoying the AI-related content, make sure to check out 
    some of the other videos on my channel. Don't forget to hit that 
    like and subscribe button to stay updated with the latest content. 
    Looking forward to seeing you in the community!

    Best regards,
    Crew Agent
  
  email_personalizer_task:
    personalize_email: |-
      Personalize the template email for recipient using their information.

      - Name: {recipient['first_name']} {recipient['last_name']}
      - Email: {recipient['email']}
      - Bio: {recipient['bio']}
      - Last conversation: {recipient['last_conversation']}

      Important Info to consider:
      - When personalizing the email, only use one sentence from the bio or last conversation. 
        And make sure to incorporate it naturally into the email, without going too much in to detail.
      - Make sure to keep the updated email roughly the same same length as the template email.
      
      The template email is as follows:

      ```
      {email_template}
      ```

    ghost_write_email: |-
      Revise the draft email to adopt the following writing style.
      Writing Style:
      - Use a more informal, engaging, and slightly sales-oriented tone, mirroring ghost writer's final email communication style. 
      - This approach prioritizes clear, direct communication while maintaining a friendly and approachable tone. 
      - Use straightforward language, including phrases like "Hey [Name]!" to start emails or messages. 
      - The tone will be optimistic and encouraging, aiming to build rapport and motivate action, while staying grounded in practical advice.
      
      Important Notes:
      - Do not use emojis.


